# Generated by Django 3.0.5 on 2020-04-09 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rank', models.IntegerField()),
                ('Neighborhood', models.CharField(max_length=200)),
                ('Population', models.IntegerField()),
                ('Home_Value', models.IntegerField()),
                ('Median_Income', models.IntegerField()),
            ],
        ),
    ]
