# Generated by Django 3.0.5 on 2020-04-09 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='Home_Value',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='income',
            name='Median_Income',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='income',
            name='Population',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='income',
            name='Rank',
            field=models.CharField(max_length=200),
        ),
    ]
