# Generated by Django 3.0.5 on 2020-04-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_app', '0002_auto_20200409_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='Home_Value',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='income',
            name='Median_Income',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='income',
            name='Population',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='income',
            name='Rank',
            field=models.IntegerField(),
        ),
    ]
