# Generated by Django 3.0.5 on 2020-04-10 09:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_app', '0005_auto_20200409_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='crime',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('Type', models.CharField(max_length=200)),
                ('Arrest', models.BooleanField()),
                ('Area_id', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(77)])),
            ],
        ),
    ]
