# Generated by Django 3.0.5 on 2020-04-10 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crime_app', '0006_crime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crime',
            name='Arrest',
        ),
        migrations.RemoveField(
            model_name='crime',
            name='Date',
        ),
    ]
