# Generated by Django 3.0.5 on 2020-04-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_app', '0007_auto_20200410_0442'),
    ]

    operations = [
        migrations.CreateModel(
            name='district_id',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Neighborhood', models.CharField(max_length=200)),
            ],
        ),
    ]
