# Generated by Django 3.0.5 on 2020-05-04 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_app', '0008_district_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='danger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=200)),
                ('Gender', models.CharField(max_length=200)),
                ('Age', models.CharField(max_length=200)),
                ('Level', models.IntegerField()),
            ],
            options={
                'unique_together': {('Type', 'Gender', 'Age')},
            },
        ),
    ]
