# Generated by Django 3.0.5 on 2020-05-04 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_app', '0009_danger'),
    ]

    operations = [
        migrations.AddField(
            model_name='crime',
            name='Time',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
