# Generated by Django 3.0.5 on 2020-05-04 21:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_app', '0012_crime_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime',
            name='Time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
