# Generated by Django 3.0.5 on 2020-05-05 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_app', '0013_auto_20200504_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danger',
            name='Level',
            field=models.FloatField(),
        ),
    ]
