# Generated by Django 3.0.5 on 2020-05-05 09:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_app', '0015_auto_20200505_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime',
            name='Area_id',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)]),
        ),
    ]
